WITH states(state_name) AS (
  VALUES
    ('Punjab'),
    ('Haryana'),
    ('Uttar Pradesh'),
    ('Rajasthan'),
    ('Maharashtra'),
    ('Madhya Pradesh'),
    ('Bihar'),
    ('Gujarat'),
    ('Tamil Nadu'),
    ('Karnataka'),
    ('West Bengal')
),
templates(template_key, title, description, category, eligibility, benefits, benefit_type, ministry, max_benefit, website_slug) AS (
  VALUES
    (
      'solar-pump',
      'Solar Pump Support',
      'Support for farmers adopting solar irrigation pumps and related infrastructure.',
      'Agriculture',
      'Farmers with cultivable land and irrigation needs.',
      ARRAY['Capital subsidy', 'Irrigation cost reduction', 'Renewable energy support'],
      'Subsidies',
      'Ministry of Agriculture and Farmers Welfare',
      'Up to Rs. 3 lakh',
      'solar-pump-support'
    ),
    (
      'micro-irrigation',
      'Micro Irrigation Mission',
      'Support for drip, sprinkler, and efficient water management systems.',
      'Agriculture',
      'Farmers and farmer groups adopting water-saving irrigation methods.',
      ARRAY['Drip irrigation support', 'Sprinkler subsidy', 'Water efficiency upgrade'],
      'Subsidies',
      'Department of Agriculture and Farmers Welfare',
      '40% to 70% assistance',
      'micro-irrigation-mission'
    ),
    (
      'crop-insurance',
      'Crop Insurance Protection',
      'Seasonal crop insurance support for notified crops and regions.',
      'Insurance',
      'Farmers cultivating notified crops in eligible regions.',
      ARRAY['Premium support', 'Weather risk cover', 'Crop loss protection'],
      'Insurance',
      'Ministry of Agriculture and Farmers Welfare',
      'Coverage as per acreage',
      'crop-insurance-protection'
    ),
    (
      'soil-health',
      'Soil Health Assistance',
      'Support for soil testing, nutrient planning, and balanced farm input use.',
      'Agriculture',
      'Farmers and collectives improving soil health practices.',
      ARRAY['Soil testing support', 'Nutrient guidance', 'Balanced input use'],
      'Subsidies',
      'Department of Agriculture Cooperation',
      'As per local sanction',
      'soil-health-assistance'
    ),
    (
      'fpo-support',
      'Farmer Producer Organization Support',
      'Infrastructure and market linkage support for FPOs and producer groups.',
      'Agriculture',
      'Registered FPOs, producer collectives, and cooperatives.',
      ARRAY['Capacity building', 'Storage support', 'Market linkage'],
      'Credit & Loan',
      'Ministry of Agriculture and Farmers Welfare',
      'Up to Rs. 15 lakh',
      'fpo-support'
    ),
    (
      'kisan-credit',
      'Kisan Credit Expansion',
      'Working capital support for seasonal crop and allied activities.',
      'Credit',
      'Eligible farmers, tenant cultivators, and allied operators meeting bank norms.',
      ARRAY['Working capital', 'Short-term crop credit', 'Interest support'],
      'Credit & Loan',
      'Department of Financial Services',
      'As per bank eligibility',
      'kisan-credit-expansion'
    ),
    (
      'agri-processing',
      'Agri Processing Upgrade',
      'Assistance for farm-gate processing, grading, and storage units.',
      'MSME',
      'Agri entrepreneurs, FPO-backed units, and registered micro enterprises.',
      ARRAY['Machinery support', 'Storage support', 'Value addition'],
      'Subsidies',
      'Ministry of Food Processing Industries',
      'Up to Rs. 20 lakh',
      'agri-processing-upgrade'
    ),
    (
      'women-enterprise',
      'Women Enterprise Support',
      'Business setup and livelihood support for women-led enterprises.',
      'Women & Child',
      'Women entrepreneurs, SHGs, and women-led micro enterprises.',
      ARRAY['Enterprise support', 'Skill enablement', 'Working capital linkage'],
      'Subsidies',
      'Ministry of Women and Child Development',
      'Up to Rs. 10 lakh',
      'women-enterprise-support'
    ),
    (
      'student-scholarship',
      'Student Scholarship Access',
      'Scholarship support for low-income students and priority categories.',
      'Education',
      'Students with enrollment proof, identity documents, and income eligibility.',
      ARRAY['Tuition support', 'DBT scholarship', 'Education continuity support'],
      'Direct Cash',
      'Ministry of Education',
      'Up to Rs. 75000 per year',
      'student-scholarship-access'
    ),
    (
      'rural-housing',
      'Rural Housing Support',
      'Support for rural house construction and housing-linked amenities.',
      'Housing',
      'Eligible rural households meeting housing and income criteria.',
      ARRAY['Housing support', 'Installment release', 'Amenity linkage'],
      'Direct Cash',
      'Ministry of Rural Development',
      'As per housing category',
      'rural-housing-support'
    ),
    (
      'health-cover',
      'Household Health Cover',
      'Financial protection support for hospitalization and select procedures.',
      'Health',
      'Eligible beneficiary households under notified health programs.',
      ARRAY['Hospitalization cover', 'Cashless treatment', 'Family health support'],
      'Insurance',
      'Ministry of Health and Family Welfare',
      'Up to Rs. 5 lakh',
      'household-health-cover'
    ),
    (
      'dairy-support',
      'Dairy Enterprise Support',
      'Support for small dairy units, chilling, and milk handling systems.',
      'Agriculture',
      'Dairy farmers, cooperatives, and small livestock entrepreneurs.',
      ARRAY['Livestock support', 'Milk handling equipment', 'Cold chain support'],
      'Subsidies',
      'Department of Animal Husbandry and Dairying',
      'Up to Rs. 12 lakh',
      'dairy-enterprise-support'
    ),
    (
      'fisheries-support',
      'Fisheries Livelihood Support',
      'Support for fish farming, hatcheries, and cold-chain facilities.',
      'Agriculture',
      'Fish farmers, fisheries groups, and eligible aquaculture units.',
      ARRAY['Pond support', 'Cold chain support', 'Input support'],
      'Subsidies',
      'Department of Fisheries',
      'Up to Rs. 18 lakh',
      'fisheries-livelihood-support'
    ),
    (
      'food-processing',
      'Food Processing Cluster Support',
      'Support for processing clusters, branding, and market access.',
      'MSME',
      'Food processing units, producer groups, and rural enterprises.',
      ARRAY['Cluster support', 'Packaging support', 'Market linkage'],
      'Subsidies',
      'Ministry of Food Processing Industries',
      'Up to Rs. 25 lakh',
      'food-processing-cluster-support'
    ),
    (
      'startup-seed',
      'Startup Seed Access',
      'Seed-stage support for innovation and rural impact startups.',
      'Startup',
      'Recognized startups with compliant registration and early-stage plans.',
      ARRAY['Seed capital', 'Mentorship', 'Pilot support'],
      'Direct Cash',
      'Department for Promotion of Industry and Internal Trade',
      'Up to Rs. 50 lakh',
      'startup-seed-access'
    ),
    (
      'artisan-credit',
      'Artisan Working Capital Support',
      'Working capital and equipment support for artisans and local makers.',
      'Credit',
      'Registered artisans, self-employed workers, and eligible producer groups.',
      ARRAY['Working capital', 'Tool purchase support', 'Market linkage'],
      'Credit & Loan',
      'Ministry of MSME',
      'Up to Rs. 5 lakh',
      'artisan-working-capital-support'
    ),
    (
      'self-help-group',
      'Self Help Group Enterprise Grant',
      'Enterprise support for self-help groups expanding local livelihoods.',
      'Women & Child',
      'Registered SHGs and women-led collective enterprises.',
      ARRAY['Enterprise grant', 'Group equipment support', 'Market linkage'],
      'Direct Cash',
      'Ministry of Rural Development',
      'Up to Rs. 8 lakh',
      'self-help-group-enterprise-grant'
    ),
    (
      'skill-youth',
      'Youth Skill Development Grant',
      'Support for job-linked skill development and certification.',
      'Education',
      'Youth applicants with identity documents and eligibility under training norms.',
      ARRAY['Training support', 'Certification support', 'Placement linkage'],
      'Direct Cash',
      'Ministry of Skill Development and Entrepreneurship',
      'Up to Rs. 50000',
      'youth-skill-development-grant'
    ),
    (
      'urban-housing',
      'Affordable Urban Housing Support',
      'Support for home improvement and affordable urban housing assistance.',
      'Housing',
      'Eligible low-income urban households and beneficiaries under notified categories.',
      ARRAY['Home improvement support', 'Housing subsidy', 'Basic services linkage'],
      'Direct Cash',
      'Ministry of Housing and Urban Affairs',
      'As per housing norms',
      'affordable-urban-housing-support'
    ),
    (
      'maternal-health',
      'Maternal and Child Health Benefit',
      'Support for maternal care, child nutrition, and institutional health access.',
      'Health',
      'Eligible pregnant women, mothers, and beneficiary households.',
      ARRAY['Maternal benefit', 'Nutrition support', 'Health facility linkage'],
      'Direct Cash',
      'Ministry of Health and Family Welfare',
      'As per program norms',
      'maternal-child-health-benefit'
    )
)
INSERT INTO public.schemes (
  external_id,
  title,
  description,
  category,
  state,
  eligibility,
  benefits,
  benefit_type,
  status,
  ministry,
  max_benefit,
  application_deadline,
  website_url
)
SELECT
  'seed-' || template_key || '-' || lower(replace(state_name, ' ', '-')) AS external_id,
  title || ' - ' || state_name AS title,
  description || ' This version is intended for applicants in ' || state_name || '.' AS description,
  category,
  state_name,
  eligibility,
  benefits,
  benefit_type,
  'active' AS status,
  ministry,
  max_benefit,
  NULL AS application_deadline,
  'https://example.gov.in/schemes/' || website_slug || '/' || lower(replace(state_name, ' ', '-')) AS website_url
FROM templates
CROSS JOIN states
ON CONFLICT (external_id) DO UPDATE
SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  state = EXCLUDED.state,
  eligibility = EXCLUDED.eligibility,
  benefits = EXCLUDED.benefits,
  benefit_type = EXCLUDED.benefit_type,
  status = EXCLUDED.status,
  ministry = EXCLUDED.ministry,
  max_benefit = EXCLUDED.max_benefit,
  application_deadline = EXCLUDED.application_deadline,
  website_url = EXCLUDED.website_url,
  updated_at = now();
